In [7]:
import pandas as pd

In [8]:
import numpy as np

In [9]:
import matplotlib.pyplot as plt

In [12]:
from pathlib import Path

matches = list(Path.home().rglob('Amazon Sale Report.csv'))
matches

[WindowsPath('C:/Users/pavan/OneDrive/Desktop/E-Commerce SalesDataset/Amazon Sale Report.csv'),
 WindowsPath('C:/Users/pavan/Downloads/archive/Amazon Sale Report.csv')]

In [13]:
amazon_df = pd.read_csv(matches[0], low_memory=False)
amazon_df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN

In [14]:
amazon_df.shape

(128975, 24)

In [15]:
amazon_df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'currency', 'Amount', 'ship-city',
       'ship-state', 'ship-postal-code', 'ship-country', 'promotion-ids',
       'B2B', 'fulfilled-by', 'Unnamed: 22'],
      dtype='object')

In [16]:
amazon_df.columns.tolist()

['index',
 'Order ID',
 'Date',
 'Status',
 'Fulfilment',
 'Sales Channel ',
 'ship-service-level',
 'Style',
 'SKU',
 'Category',
 'Size',
 'ASIN',
 'Courier Status',
 'Qty',
 'currency',
 'Amount',
 'ship-city',
 'ship-state',
 'ship-postal-code',
 'ship-country',
 'promotion-ids',
 'B2B',
 'fulfilled-by',
 'Unnamed: 22']

In [17]:
amazon_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

In [18]:
amazon_df.isnull().sum().sort_values(ascending = False)

fulfilled-by          89698
promotion-ids         49153
Unnamed: 22           49050
currency               7795
Amount                 7795
Courier Status         6872
ship-country             33
ship-postal-code         33
ship-state               33
ship-city                33
ship-service-level        0
Style                     0
Date                      0
B2B                       0
Status                    0
Fulfilment                0
Sales Channel             0
Qty                       0
Order ID                  0
ASIN                      0
Size                      0
Category                  0
SKU                       0
index                     0
dtype: int64

In [19]:
amazon_df.duplicated().sum()

np.int64(0)

In [20]:
amazon_clean = amazon_df.copy()

In [21]:
amazon_clean = amazon_clean.drop(columns=['index', 'Unnamed: 22'])

In [22]:
amazon_clean.shape

(128975, 22)

In [23]:
amazon_clean.columns = amazon_clean.columns.str.strip()

In [24]:
amazon_clean.columns.tolist()

['Order ID',
 'Date',
 'Status',
 'Fulfilment',
 'Sales Channel',
 'ship-service-level',
 'Style',
 'SKU',
 'Category',
 'Size',
 'ASIN',
 'Courier Status',
 'Qty',
 'currency',
 'Amount',
 'ship-city',
 'ship-state',
 'ship-postal-code',
 'ship-country',
 'promotion-ids',
 'B2B',
 'fulfilled-by']

In [25]:
amazon_clean.columns = amazon_clean.columns.str.lower()

In [26]:
amazon_clean.columns.tolist()

['order id',
 'date',
 'status',
 'fulfilment',
 'sales channel',
 'ship-service-level',
 'style',
 'sku',
 'category',
 'size',
 'asin',
 'courier status',
 'qty',
 'currency',
 'amount',
 'ship-city',
 'ship-state',
 'ship-postal-code',
 'ship-country',
 'promotion-ids',
 'b2b',
 'fulfilled-by']

In [27]:
amazon_clean.columns = amazon_clean.columns.str.replace('-','_', regex = False)

In [28]:
amazon_clean.columns.tolist()

['order id',
 'date',
 'status',
 'fulfilment',
 'sales channel',
 'ship_service_level',
 'style',
 'sku',
 'category',
 'size',
 'asin',
 'courier status',
 'qty',
 'currency',
 'amount',
 'ship_city',
 'ship_state',
 'ship_postal_code',
 'ship_country',
 'promotion_ids',
 'b2b',
 'fulfilled_by']

In [29]:
amazon_clean['date'].dtype

dtype('O')

In [30]:
amazon_clean['date'] = pd.to_datetime(
    amazon_clean['date'],
    format = '%m-%d-%y'
)

In [31]:
amazon_clean['date'].dtype

dtype('<M8[ns]')

In [34]:
amazon_clean['date'].min() # This is checking the range covered by the datset

Timestamp('2022-03-31 00:00:00')

In [35]:
amazon_clean['date'].max()

Timestamp('2022-06-29 00:00:00')

In [36]:
amazon_clean.loc[
    amazon_clean['amount'].isnull(),
    'status'].value_counts()

status
Cancelled                       7566
Shipped                          208
Shipped - Delivered to Buyer       8
Shipping                           8
Shipped - Returned to Seller       3
Pending                            2
Name: count, dtype: int64

In [37]:
amazon_clean['amount_missing'] = amazon_clean['amount'].isnull()

In [38]:
amazon_clean['amount_missing'].value_counts()

amount_missing
False    121180
True       7795
Name: count, dtype: int64

In [40]:
amazon_clean['amount'].isnull().mean() * 100

np.float64(6.043806939329328)

In [41]:
round(amazon_clean['amount'].isnull().mean() * 100,2)  #It reduce the decimal number

np.float64(6.04)

In [42]:
amazon_clean[['amount','currency']].isnull().sum()

amount      7795
currency    7795
dtype: int64

In [43]:
(amazon_clean['amount'].isnull()
    ==
    amazon_clean['currency'].isnull()
).all()

np.True_

In [44]:
amazon_clean['currency'] = amazon_clean['currency'].fillna('INR')

In [45]:
amazon_clean['currency'].isnull().sum()

np.int64(0)

In [46]:
amazon_clean[['currency']].head()

  currency
0      INR
1      INR
2      INR
3      INR
4      INR

In [47]:
amazon_clean[['ship_city','ship_state','ship_postal_code','ship_country']].isnull().sum()

ship_city           33
ship_state          33
ship_postal_code    33
ship_country        33
dtype: int64

In [48]:
amazon_clean['ship_city'] = amazon_clean['ship_city'].fillna('Unknown')

In [49]:
amazon_clean['ship_country'] = amazon_clean['ship_country'].fillna('Unknown')

In [50]:
amazon_clean['ship_state'] = amazon_clean['ship_state'].fillna('Unknown')

In [51]:
amazon_clean[
    ['ship_city','ship_country','ship_state']].isnull().sum()

ship_city       0
ship_country    0
ship_state      0
dtype: int64

In [52]:
amazon_clean['ship_postal_code'] = (
    amazon_clean['ship_postal_code'].astype('Int64')
)

In [53]:
amazon_clean['ship_postal_code'] = ( 
    amazon_clean['ship_postal_code'].astype('string'))

In [54]:
amazon_clean['ship_postal_code'] = (
    amazon_clean['ship_postal_code'].fillna('Unknown'))

In [55]:
amazon_clean['ship_postal_code'].isnull().sum()

np.int64(0)

In [56]:
amazon_clean['promotion_applied'] = (
    amazon_clean['promotion_ids'].notnull()
)

In [57]:
amazon_clean['promotion_applied'].value_counts()

promotion_applied
True     79822
False    49153
Name: count, dtype: int64

In [58]:
amazon_clean = amazon_clean.rename(
    columns={'promotion_applied': 'promotion_recorded'}
)

In [59]:
amazon_clean['promotion_ids'] = (
    amazon_clean['promotion_ids'].fillna('No Promotion Recorded')
)

In [60]:
amazon_clean['promotion_ids'].isnull().sum()

np.int64(0)

In [63]:
pd.crosstab(
    amazon_clean['fulfilment'],
    amazon_clean['fulfilled_by'],
    dropna = False
)

fulfilled_by  Amazon  Easy Ship
fulfilment
Amazon         89698          0
Merchant           0      39277

In [64]:
amazon_clean['fulfilled_by'] = (
    amazon_clean['fulfilled_by'].fillna('Amazon')
)

In [65]:
amazon_clean['fulfilled_by'].value_counts()

fulfilled_by
Amazon       89698
Easy Ship    39277
Name: count, dtype: int64

In [66]:
amazon_clean.loc[
    amazon_clean['courier status'].isnull(),
    'status'].value_counts()

status
Cancelled                       6861
Shipped - Delivered to Buyer       8
Shipped - Returned to Seller       3
Name: count, dtype: int64

In [67]:
cancelled_mask = (
    amazon_clean['courier status'].isnull()
    &
    amazon_clean['status'].eq('cancelled')
)

In [68]:
amazon_clean.loc[cancelled_mask, 'courier status'] = 'Not Shipped'

In [69]:
amazon_clean['courier status'] = (
    amazon_clean['courier status'].fillna('Unknown')
)

In [70]:
amazon_clean['courier status'].isnull().sum()

np.int64(0)

In [71]:
amazon_clean['category'].value_counts()

category
Set              50284
kurta            49877
Western Dress    15500
Top              10622
Ethnic Dress      1159
Blouse             926
Bottom             440
Saree              164
Dupatta              3
Name: count, dtype: int64

In [72]:
amazon_clean['category'] = (
    amazon_clean['category'].str.strip().str.title()
)

In [73]:
amazon_clean['category'].value_counts()

category
Set              50284
Kurta            49877
Western Dress    15500
Top              10622
Ethnic Dress      1159
Blouse             926
Bottom             440
Saree              164
Dupatta              3
Name: count, dtype: int64

In [74]:
amazon_clean['size'].value_counts()

size
M       22711
L       22132
XL      20876
XXL     18096
S       17090
3XL     14816
XS      11161
6XL       738
5XL       550
4XL       427
Free      378
Name: count, dtype: int64

In [75]:
amazon_clean['qty'].value_counts().sort_index()

qty
0      12807
1     115780
2        341
3         32
4          9
5          2
8          1
9          1
13         1
15         1
Name: count, dtype: int64

In [76]:
amazon_clean['zero_qty'] = amazon_clean['qty'].eq(0)

In [77]:
amazon_clean['zero_qty'].value_counts()

zero_qty
False    116168
True      12807
Name: count, dtype: int64

In [78]:
amazon_clean[['qty', 'zero_qty']].head(10)

   qty  zero_qty
0    0      True
1    1     False
2    1     False
3    0      True
4    1     False
5    1     False
6    1     False
7    1     False
8    0      True
9    1     False

In [79]:
amazon_clean['amount'].describe()

count    121180.000000
mean        648.561465
std         281.211687
min           0.000000
25%         449.000000
50%         605.000000
75%         788.000000
max        5584.000000
Name: amount, dtype: float64

In [80]:
amazon_clean['amount'].eq(0).sum()

np.int64(2343)

In [81]:
amazon_clean.loc[
    amazon_clean['amount'] == 0,
    'status'].value_counts()

status
Shipped                          1518
Shipped - Delivered to Buyer      716
Shipped - Returned to Seller       51
Shipped - Picked Up                28
Pending                            17
Pending - Waiting for Pick Up       9
Shipped - Lost in Transit           2
Shipped - Returning to Seller       2
Name: count, dtype: int64

In [82]:
amazon_clean['zero_amount'] = (
    amazon_clean['amount'] == 0 )

In [83]:
amazon_clean['zero_amount'].value_counts()

zero_amount
False    126632
True       2343
Name: count, dtype: int64

In [84]:
amazon_clean.columns = (
    amazon_clean.columns.str.replace(' ','_', regex = False)
)

In [85]:
amazon_clean.columns.tolist()

['order_id',
 'date',
 'status',
 'fulfilment',
 'sales_channel',
 'ship_service_level',
 'style',
 'sku',
 'category',
 'size',
 'asin',
 'courier_status',
 'qty',
 'currency',
 'amount',
 'ship_city',
 'ship_state',
 'ship_postal_code',
 'ship_country',
 'promotion_ids',
 'b2b',
 'fulfilled_by',
 'amount_missing',
 'promotion_recorded',
 'zero_qty',
 'zero_amount']

In [84]:
amazon_clean.columns = (
    amazon_clean.columns.str.replace('-','_', regex = False)
)

In [85]:
amazon_clean.columns.tolist()

['order_id',
 'date',
 'status',
 'fulfilment',
 'sales_channel',
 'ship_service_level',
 'style',
 'sku',
 'category',
 'size',
 'asin',
 'courier_status',
 'qty',
 'currency',
 'amount',
 'ship_city',
 'ship_state',
 'ship_postal_code',
 'ship_country',
 'promotion_ids',
 'b2b',
 'fulfilled_by',
 'amount_missing',
 'promotion_recorded',
 'zero_qty',
 'zero_amount']

In [86]:
amazon_clean['order_id'].nunique()

120378

In [87]:
amazon_clean.duplicated(
    subset = ['order_id', 'sku']).sum()

np.int64(7)

In [88]:
amazon_clean.loc[
    amazon_clean.duplicated(
        subset = ['order_id','sku'],
        keep = False),
    ['order_id','sku','date','status','qty','amount']].sort_values(['order_id', 'sku'])

                  order_id              sku       date     status  qty  amount
85790  171-3249942-2207542  SET323-KR-NP-XL 2022-05-03    Shipped    1   939.0
85791  171-3249942-2207542  SET323-KR-NP-XL 2022-05-03    Shipped    1   939.0
79844  171-9628368-5329958       J0329-KR-L 2022-05-07  Cancelled    0     NaN
79845  171-9628368-5329958       J0329-KR-L 2022-05-07  Cancelled    0     NaN
86418  405-8669298-3850736  MEN5025-KR-XXXL 2022-05-03    Shipped    1   533.0
86419  405-8669298-3850736  MEN5025-KR-XXXL 2022-05-03    Shipped    1   533.0
30660  406-0372545-6086735   SET197-KR-NP-L 2022-04-12  Cancelled    0     NaN
30661  406-0372545-6086735   SET197-KR-NP-L 2022-04-12  Cancelled    0     NaN
98954  407-4853873-4978725      J0230-SKD-M 2022-06-22    Shipped    1  1163.0
98955  407-4853873-4978725      J0230-SKD-M 2022-06-22    Shipped    1  1163.0
52330  407-8364731-6449117     JNE3769-KR-L 2022-05-29    Shipped    0     NaN
52333  407-8364731-6449117     JNE3769-KR-L 2022-05-29    Shipped    1   487.0
41291  408-0373839-4433120     JNE3501-KR-M 2022-04-05  Cancelled    0     NaN
41292  408-0373839-4433120     JNE3501-KR-M 2022-04-05  Cancelled    0     NaN

In [89]:
amazon_clean['repeated_order_sku'] = (
    amazon_clean.duplicated(
        subset = ['order_id','sku'],
        keep = False)
)

In [90]:
amazon_clean['repeated_order_sku'].value_counts()

repeated_order_sku
False    128961
True         14
Name: count, dtype: int64

In [94]:
amazon_clean['status'].value_counts()

status
Shipped                          77804
Shipped - Delivered to Buyer     28769
Cancelled                        18332
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

In [95]:
status_mapping = {
    'Shipped - Delivered to Buyer': 'Delivered',

    'Shipped': 'Shipped / In Process',
    'Shipped - Picked Up': 'Shipped / In Process',
    'Shipped - Out for Delivery': 'Shipped / In Process',
    'Shipping': 'Shipped / In Process',

    'Cancelled': 'Cancelled',

    'Pending': 'Pending',
    'Pending - Waiting for Pick Up': 'Pending',

    'Shipped - Returned to Seller': 'Return / Rejected',
    'Shipped - Returning to Seller': 'Return / Rejected',
    'Shipped - Rejected by Buyer': 'Return / Rejected',

    'Shipped - Lost in Transit': 'Delivery Issue',
    'Shipped - Damaged': 'Delivery Issue'
}

In [96]:
amazon_clean['status_group'] = (
    amazon_clean['status'].map(status_mapping)
)

In [97]:
amazon_clean['status_group'].value_counts()

status_group
Shipped / In Process    78820
Delivered               28769
Cancelled               18332
Return / Rejected        2109
Pending                   939
Delivery Issue              6
Name: count, dtype: int64

In [98]:
amazon_clean['b2b'].value_counts()

b2b
False    128104
True        871
Name: count, dtype: int64

In [99]:
amazon_clean['customer_type'] = (
    amazon_clean['b2b'].map({
        False: 'B2C',
        True: 'B2B'})
)

In [100]:
amazon_clean['customer_type'].value_counts()

customer_type
B2C    128104
B2B       871
Name: count, dtype: int64

In [101]:
amazon_clean['sales_channel'].value_counts()

sales_channel
Amazon.in     128851
Non-Amazon       124
Name: count, dtype: int64

In [104]:
amazon_clean['ship_service_level'].value_counts()

ship_service_level
Expedited    88615
Standard     40360
Name: count, dtype: int64

In [105]:
amazon_clean['ship_state'] = (
        amazon_clean['ship_state'].str.strip().str.upper()
)

In [106]:
amazon_clean['ship_state'].value_counts()

ship_state
MAHARASHTRA               22260
KARNATAKA                 17326
TAMIL NADU                11483
TELANGANA                 11330
UTTAR PRADESH             10638
DELHI                      6967
KERALA                     6585
WEST BENGAL                5963
ANDHRA PRADESH             5430
GUJARAT                    4489
HARYANA                    4415
RAJASTHAN                  2711
MADHYA PRADESH             2529
ODISHA                     2136
BIHAR                      2114
PUNJAB                     1917
ASSAM                      1663
UTTARAKHAND                1553
JHARKHAND                  1456
GOA                        1137
CHHATTISGARH                909
HIMACHAL PRADESH            788
JAMMU & KASHMIR             702
PUDUCHERRY                  350
CHANDIGARH                  333
MANIPUR                     316
ANDAMAN & NICOBAR           257
MEGHALAYA                   207
SIKKIM                      205
NAGALAND                    185
TRIPURA                     151
ARUNACHAL PRADESH           146
NEW DELHI                    81
MIZORAM                      76
DADRA AND NAGAR              70
LADAKH                       43
UNKNOWN                      33
LAKSHADWEEP                   4
ORISSA                        3
RAJSHTHAN                     3
RJ                            2
NL                            2
RAJSTHAN                      2
PUNJAB/MOHALI/ZIRAKPUR        1
PB                            1
APO                           1
AR                            1
PONDICHERRY                   1
Name: count, dtype: int64

In [107]:
amazon_clean['ship_state'].nunique()

48

In [108]:
state_corrections = {
    'NEW DELHI': 'DELHI',
    'RAJSHTHAN': 'RAJASTHAN',
    'RAJSTHAN': 'RAJASTHAN',
    'RJ': 'RAJASTHAN',
    'ORISSA': 'ODISHA',
    'PONDICHERRY': 'PUDUCHERRY',
    'PUNJAB/MOHALI/ZIRAKPUR': 'PUNJAB',
    'PB': 'PUNJAB',
    'NL': 'NAGALAND',
    'AR': 'ARUNACHAL PRADESH',
    'APO': 'UNKNOWN',
    'ANDAMAN & NICOBAR': 'ANDAMAN AND NICOBAR ISLANDS',
    'JAMMU & KASHMIR': 'JAMMU AND KASHMIR',
    'DADRA AND NAGAR':
    'DADRA AND NAGAR HAVELI AND DAMAN AND DIU'
}

In [109]:
amazon_clean['ship_state'] = (
    amazon_clean['ship_state'].replace(state_corrections))

In [110]:
amazon_clean['ship_state'].nunique()

37

In [111]:
amazon_clean['ship_city'] = (amazon_clean['ship_city'].str.strip().str.upper())

In [112]:
amazon_clean['ship_city'].nunique()

7298

In [113]:
amazon_clean['ship_country'].value_counts()

ship_country
IN         128942
Unknown        33
Name: count, dtype: int64

In [114]:
amazon_clean['ship_country'] = (
    amazon_clean['ship_country'].str.upper()
)

In [115]:
remaining_missing = amazon_clean.isnull().sum()
remaining_missing[remaining_missing > 0]

amount    7795
dtype: int64

In [116]:
amazon_clean['year'] = amazon_clean['date'].dt.year

In [117]:
amazon_clean['month_number'] = amazon_clean['date'].dt.month

In [122]:
amazon_clean['month_name'] = amazon_clean['date'].dt.month_name()

In [123]:
amazon_clean[
    ['date', 'year', 'month_number', 'month_name']
].head()

        date  year  month_number month_name
0 2022-04-30  2022             4      April
1 2022-04-30  2022             4      April
2 2022-04-30  2022             4      April
3 2022-04-30  2022             4      April
4 2022-04-30  2022             4      April

In [124]:
amazon_clean['year'] = amazon_clean['date'].dt.year

In [125]:
amazon_clean[['date', 'year']].head()

        date  year
0 2022-04-30  2022
1 2022-04-30  2022
2 2022-04-30  2022
3 2022-04-30  2022
4 2022-04-30  2022

In [128]:
amazon_clean['month_number'] = (
    amazon_clean['date'].dt.month)

In [129]:
amazon_clean[['date','month_number']].head()

        date  month_number
0 2022-04-30             4
1 2022-04-30             4
2 2022-04-30             4
3 2022-04-30             4
4 2022-04-30             4

In [133]:
amazon_clean['month_name'] = (
    amazon_clean['date'].dt.month_name()
)

In [134]:
amazon_clean[
    ['date', 'month_number', 'month_name']
].head()

        date  month_number month_name
0 2022-04-30             4      April
1 2022-04-30             4      April
2 2022-04-30             4      April
3 2022-04-30             4      April
4 2022-04-30             4      April

In [136]:
amazon_clean['year_month'] = (
    amazon_clean['date'].dt.to_period('M').astype(str)
)

In [137]:
amazon_clean[['date' , 'year_month']].head()

        date year_month
0 2022-04-30    2022-04
1 2022-04-30    2022-04
2 2022-04-30    2022-04
3 2022-04-30    2022-04
4 2022-04-30    2022-04

In [138]:
amazon_clean['day_name'] = (
    amazon_clean['date'].dt.day_name())

In [139]:
amazon_clean[['date', 'day_name']].head()

        date  day_name
0 2022-04-30  Saturday
1 2022-04-30  Saturday
2 2022-04-30  Saturday
3 2022-04-30  Saturday
4 2022-04-30  Saturday

In [140]:
amazon_clean['is_weekend'] = (
    amazon_clean['day_name'].isin(['Saturday','Sunday'])
)

In [141]:
amazon_clean['is_weekend'].value_counts()

is_weekend
False    90832
True     38143
Name: count, dtype: int64

In [142]:
amazon_clean.insert(0,'order_line_id',
                    range(1,len(amazon_clean) + 1)
                   )

In [143]:
amazon_clean[['order_line_id', 'order_id', 'sku']].head()

   order_line_id             order_id              sku
0              1  405-8078784-5731545   SET389-KR-NP-S
1              2  171-9198151-1101146  JNE3781-KR-XXXL
2              3  404-0687676-7273146    JNE3371-KR-XL
3              4  403-9615377-8133951       J0341-DR-L
4              5  407-1069790-7240320  JNE3671-TU-XXXL

In [144]:
amazon_clean['order_line_id'].nunique() == len(amazon_clean)

True

In [145]:
amazon_clean[
    ['order_line_id', 'order_id', 'date', 'sku', 'status', 'qty']
].isnull().sum()

order_line_id    0
order_id         0
date             0
sku              0
status           0
qty              0
dtype: int64

In [1]:
output_path = (
    matches[0].parent / 'Amazon_Sales_Cleaned.csv'
)

NameError: name 'matches' is not defined

In [147]:
amazon_clean.to_csv(
    output_path,
    index=False
)

In [149]:
output_path

WindowsPath('C:/Users/pavan/OneDrive/Desktop/E-Commerce SalesDataset/Amazon_Sales_Cleaned.csv')

In [150]:
inventory_path = (
    matches[0].parent / 'Sale Report.csv'
)

In [152]:
inventory_df = pd.read_csv(
    inventory_path,
    low_memory=False
)

In [154]:
inventory_df.head()

   index       SKU Code Design No.  Stock       Category Size Color
0      0    AN201-RED-L      AN201    5.0  AN : LEGGINGS    L   Red
1      1    AN201-RED-M      AN201    5.0  AN : LEGGINGS    M   Red
2      2    AN201-RED-S      AN201    3.0  AN : LEGGINGS    S   Red
3      3   AN201-RED-XL      AN201    6.0  AN : LEGGINGS   XL   Red
4      4  AN201-RED-XXL      AN201    3.0  AN : LEGGINGS  XXL   Red

In [155]:
inventory_df.shape

(9271, 7)

In [156]:
inventory_df.columns.tolist()

['index', 'SKU Code', 'Design No.', 'Stock', 'Category', 'Size', 'Color']

In [157]:
inventory_clean = inventory_df.copy()

In [22]:
inventory_clean = inventory_clean.drop(columns = ['index']) # Here i have run the twice hence error

KeyError: "['index'] not found in axis"

In [162]:
inventory_clean.shape

(9271, 6)

In [23]:
cleaned_file = (
    project_folder / 'Amazon_Sales_Cleaned.csv'
)

cleaned_file.exists()

True

In [5]:
from pathlib import Path

In [6]:
import pandas as pd

In [7]:
import numpy as np

In [8]:
import matplotlib.pyplot as plt

In [9]:
project_folder = Path(r'C:\Users\pavan\OneDrive\Desktop\E-Commerce SalesDataset')

In [10]:
amazon_clean = pd.read_csv(project_folder / 'Amazon_Sales_Cleaned.csv',
                           parse_dates = ['date'],
                           low_memory = False)

In [13]:
inventory_df = pd.read_csv(project_folder /'Sale Report.csv',
                           low_memory = False)

In [16]:
inventory_clean = inventory_df.copy()

In [17]:
inventory_clean = inventory_clean.drop(
    columns=['index']
)

In [19]:
inventory_clean = inventory_clean.rename(
    columns={
        'SKU Code': 'sku',
        'Design No.': 'design_no',
        'Stock': 'stock',
        'Category': 'category',
        'Size': 'size',
        'Color': 'color'}
)

In [20]:
inventory_clean.head()

             sku design_no  stock       category size color
0    AN201-RED-L     AN201    5.0  AN : LEGGINGS    L   Red
1    AN201-RED-M     AN201    5.0  AN : LEGGINGS    M   Red
2    AN201-RED-S     AN201    3.0  AN : LEGGINGS    S   Red
3   AN201-RED-XL     AN201    6.0  AN : LEGGINGS   XL   Red
4  AN201-RED-XXL     AN201    3.0  AN : LEGGINGS  XXL   Red

In [25]:
inventory_clean.isnull().sum()

sku          83
design_no    36
stock        36
category     45
size         36
color        45
dtype: int64

In [26]:
inventory_clean.isnull().all(axis=1).sum()

np.int64(36)

In [27]:
inventory_clean = inventory_clean.dropna(how = 'all')

In [28]:
inventory_clean.shape

(9235, 6)

In [29]:
inventory_clean = inventory_clean.reset_index(drop = True)

In [30]:
inventory_clean.head()

             sku design_no  stock       category size color
0    AN201-RED-L     AN201    5.0  AN : LEGGINGS    L   Red
1    AN201-RED-M     AN201    5.0  AN : LEGGINGS    M   Red
2    AN201-RED-S     AN201    3.0  AN : LEGGINGS    S   Red
3   AN201-RED-XL     AN201    6.0  AN : LEGGINGS   XL   Red
4  AN201-RED-XXL     AN201    3.0  AN : LEGGINGS  XXL   Red

In [31]:
inventory_clean.isnull().sum()

sku          47
design_no     0
stock         0
category      9
size          0
color         9
dtype: int64

In [1]:
inventory_missing_sku = inventory_clean[
    inventory_clean['sku'].isnull()
].copy()

inventory_missing_sku.shape

NameError: name 'inventory_clean' is not defined

In [2]:
from pathlib import Path
import pandas as pd

project_folder = Path(
    r'C:\Users\pavan\OneDrive\Desktop\E-Commerce SalesDataset'
)

inventory_df = pd.read_csv(project_folder / 'Sale Report.csv')

inventory_clean = inventory_df.copy()

inventory_clean = inventory_clean.drop(
    columns=['index'],
    errors='ignore'
)

inventory_clean = inventory_clean.rename(columns={
    'SKU Code': 'sku',
    'Design No.': 'design_no',
    'Stock': 'stock',
    'Category': 'category',
    'Size': 'size',
    'Color': 'color'
})

inventory_clean = inventory_clean.dropna(how='all')
inventory_clean = inventory_clean.reset_index(drop=True)

In [3]:
inventory_clean.shape

(9235, 6)

In [4]:
inventory_missing_sku = inventory_clean[
    inventory_clean['sku'].isnull()].copy()

In [5]:
inventory_missing_sku.shape

(47, 6)

In [10]:
inventory_missing_sku.head(10)

     sku design_no  stock       category  size       color
135  NaN     BL086    1.0         BLOUSE  FREE        Blue
142  NaN     BL087    0.0         BLOUSE  FREE  Multicolor
197  NaN     BL097    1.0         BLOUSE  XXXL      Maroon
198  NaN     BL098    2.0         BLOUSE  FREE       Brown
223  NaN     BL102    1.0         BLOUSE  FREE   Navy Blue
248  NaN     BL109    2.0         BLOUSE  FREE        Gold
273  NaN     BL113    0.0         BLOUSE  XXXL      Maroon
546  NaN     CH203    0.0  AN : LEGGINGS  FREE      Maroon
901  NaN     J0055    0.0            NaN     S         NaN
902  NaN     J0055    0.0            NaN    XL         NaN

In [12]:
inventory_clean['sku_missing'] = inventory_clean['sku'].isnull()

In [15]:
inventory_clean['sku_missing'].value_counts()

sku_missing
False    9188
True       47
Name: count, dtype: int64

In [16]:
inventory_missing_details = inventory_clean[
    inventory_clean['category'].isnull() |
    inventory_clean['color'].isnull()].copy()

In [17]:
inventory_missing_details

      sku design_no  stock category  size color  sku_missing
901   NaN     J0055    0.0      NaN     S   NaN         True
902   NaN     J0055    0.0      NaN    XL   NaN         True
903   NaN     J0055    0.0      NaN    XS   NaN         True
904   NaN     J0055    0.0      NaN   XXL   NaN         True
938   NaN     J0071    0.0      NaN     S   NaN         True
939   NaN     J0071    0.0      NaN    XS   NaN         True
940   NaN     J0071    0.0      NaN  XXXL   NaN         True
7593  NaN    SET111    0.0      NaN     M   NaN         True
7594  NaN    SET111    0.0      NaN  XXXL   NaN         True

In [18]:
inventory_clean['category'] = inventory_clean['category'].fillna('Unknown')

inventory_clean['color'] = inventory_clean['color'].fillna('Unknown')

In [19]:
inventory_clean[['category', 'color']].isnull().sum()

category    0
color       0
dtype: int64

In [23]:
inventory_clean['stock'].describe()

count    9235.000000
mean       26.246454
std        58.462891
min         0.000000
25%         3.000000
50%         8.000000
75%        31.000000
max      1234.000000
Name: stock, dtype: float64

In [24]:
(inventory_clean['stock'] ==0).sum()

np.int64(584)

In [25]:
inventory_clean['stock_status'] = inventory_clean['stock'].eq(0).map({
    True: 'Out of Stock',
    False: 'In Stock'})

In [26]:
inventory_clean['stock_status'].value_counts()

stock_status
In Stock        8651
Out of Stock     584
Name: count, dtype: int64

In [27]:
inventory_clean['stock_status'] = inventory_clean['stock'].apply(
    lambda x: 'Out of Stock' if x == 0
    else 'Low Stock' if x <= 5
    else 'In Stock'
)

In [28]:
inventory_clean['stock_status'].value_counts()

stock_status
In Stock        5278
Low Stock       3373
Out of Stock     584
Name: count, dtype: int64

In [29]:
(inventory_clean['stock'] % 1 == 0).all()

np.True_

In [30]:
inventory_clean['stock'] = inventory_clean['stock'].astype(int)

In [31]:
inventory_clean.head()

,sku,design_no,stock,category,size,color,sku_missing,stock_status
0,AN201-RED-L,AN201,5,AN : LEGGINGS,L,Red,False,Low Stock
1,AN201-RED-M,AN201,5,AN : LEGGINGS,M,Red,False,Low Stock
2,AN201-RED-S,AN201,3,AN : LEGGINGS,S,Red,False,Low Stock
3,AN201-RED-XL,AN201,6,AN : LEGGINGS,XL,Red,False,In Stock
4,AN201-RED-XXL,AN201,3,AN : LEGGINGS,XXL,Red,False,Low Stock

In [32]:
inventory_clean['category'].value_counts()

category
KURTA                   3726
KURTA SET               1598
SET                     1050
TOP                      865
DRESS                    700
BLOUSE                   241
NIGHT WEAR               217
TUNIC                    154
SAREE                    147
AN : LEGGINGS            131
PALAZZO                   91
PANT                      91
CROP TOP                  42
SHARARA                   40
LEHENGA CHOLI             35
KURTI                     28
SKIRT                     20
BOTTOM                    19
CARDIGAN                  17
Unknown                    9
JUMPSUIT                   7
CROP TOP WITH PLAZZO       7
Name: count, dtype: int64

In [33]:
inventory_clean['category'] = (
    inventory_clean['category']
    .replace({
        'AN : LEGGINGS': 'Leggings',
        'CROP TOP WITH PLAZZO': 'Crop Top With Palazzo'
    })
    .str.strip()
    .str.title()
)

In [34]:
inventory_clean['category'].value_counts()

category
Kurta                    3726
Kurta Set                1598
Set                      1050
Top                       865
Dress                     700
Blouse                    241
Night Wear                217
Tunic                     154
Saree                     147
Leggings                  131
Palazzo                    91
Pant                       91
Crop Top                   42
Sharara                    40
Lehenga Choli              35
Kurti                      28
Skirt                      20
Bottom                     19
Cardigan                   17
Unknown                     9
Jumpsuit                    7
Crop Top With Palazzo       7
Name: count, dtype: int64

In [35]:
inventory_clean['size'].value_counts()

size
S       1353
M       1342
XL      1340
XXL     1338
L       1335
XS      1115
XXXL    1077
FREE     223
5XL       40
6XL       38
4XL       34
Name: count, dtype: int64

In [36]:
inventory_clean['size'] = (
    inventory_clean['size']
    .str.strip()
    .str.upper()
    .replace({'FREE': 'Free'})
)

In [37]:
inventory_clean['size'].value_counts()

size
S       1353
M       1342
XL      1340
XXL     1338
L       1335
XS      1115
XXXL    1077
Free     223
5XL       40
6XL       38
4XL       34
Name: count, dtype: int64

In [38]:
inventory_clean['color'].value_counts()

color
Blue            782
Pink            779
Black           659
Green           641
Maroon          485
               ...
CORAL             7
Taupe             6
AQUA GREEN        5
Chiku             1
NO REFERENCE      1
Name: count, Length: 63, dtype: int64

In [39]:
inventory_clean['color'] = (
    inventory_clean['color']
    .str.strip()
    .str.title()
    .replace({'No Reference': 'Unknown'})
)

In [40]:
inventory_clean['color'].value_counts()

color
Blue               782
Pink               779
Black              659
Green              641
Maroon             485
Grey               457
White              413
Teal               384
Mustard            377
Yellow             350
Peach              348
Red                344
Navy Blue          342
Light Green        282
Cream              228
Beige              209
Off White          206
Multicolor         204
Brown              196
Orange             178
Sea Green          133
Sky Blue           102
Turquoise Blue     101
Wine                87
Turquoise           83
Magenta             70
Light Pink          68
Rust                60
Dark Green          58
Olive               56
Olive Green         52
Purple              50
Teal Green          47
Dark Blue           47
Turquoise Green     45
Gold                43
Mauve               27
Coral               21
Light Blue          21
Teal Blue           17
Light Yellow        17
Navy                14
Powder Blue         14
Light Brown         14
Indigo              14
Lemon               14
Burgundy            12
Mint Green          11
Unknown             10
Lemon Yellow         9
Coral Orange         7
Coral Pink           7
Lime Green           7
Charcoal             7
Khaki                7
Mint                 7
Taupe                6
Aqua Green           5
Chiku                1
Name: count, dtype: int64

In [41]:
inventory_clean.duplicated().sum()

np.int64(3)

In [42]:
duplicate_rows = inventory_clean[
    inventory_clean.duplicated(keep=False)
].sort_values(['sku', 'design_no', 'size'])

duplicate_rows

      sku design_no  stock category  size  color  sku_missing  stock_status
83  #REF!     BL021      0   Blouse  Free  Black        False  Out of Stock
84  #REF!     BL021      0   Blouse  Free  Black        False  Out of Stock
86  #REF!     BL021      0   Blouse  Free  Black        False  Out of Stock
88  #REF!     BL022      0   Blouse  Free  Beige        False  Out of Stock
89  #REF!     BL022      0   Blouse  Free  Beige        False  Out of Stock

In [43]:
inventory_clean = (
    inventory_clean
    .drop_duplicates()
    .reset_index(drop=True)
)

In [44]:
inventory_clean.shape

(9232, 8)

In [46]:
inventory_clean['sku'] = inventory_clean['sku'].replace('#REF!', pd.NA)

inventory_clean['sku_missing'] = inventory_clean['sku'].isnull()

In [47]:
inventory_clean['sku_missing'].value_counts()

sku_missing
False    9173
True       59
Name: count, dtype: int64

In [48]:
inventory_clean['sku'].eq('#REF!').sum()

np.int64(0)

In [49]:
inventory_clean.loc[
    inventory_clean['sku'].notna(),
    'sku'
].duplicated().sum()

np.int64(4)

In [50]:
duplicate_skus = inventory_clean[
    inventory_clean['sku'].notna() &
    inventory_clean['sku'].duplicated(keep=False)
].sort_values('sku')

duplicate_skus

,sku,design_no,stock,category,size,color,sku_missing,stock_status
3929,PJNE3404-KR-4XL,JNE3404,0,Kurta,4XL,Wine,False,Out of Stock
7205,PJNE3404-KR-4XL,PJNE3404,23,Kurta,4XL,Mauve,False,In Stock
3930,PJNE3404-KR-5XL,JNE3404,0,Kurta,5XL,Wine,False,Out of Stock
7206,PJNE3404-KR-5XL,PJNE3404,2,Kurta,5XL,Mauve,False,Low Stock
3938,PJNE3405-KR-5XL,JNE3405,0,Kurta,5XL,Pink,False,Out of Stock
7209,PJNE3405-KR-5XL,PJNE3405,158,Kurta,5XL,Pink,False,In Stock
3939,PJNE3405-KR-6XL,JNE3405,0,Kurta,6XL,Pink,False,Out of Stock
7210,PJNE3405-KR-6XL,PJNE3405,149,Kurta,6XL,Pink,False,In Stock

In [51]:
inventory_clean['sku_duplicate'] = (
    inventory_clean['sku'].notna() &
    inventory_clean['sku'].duplicated(keep=False)
)

In [52]:
inventory_clean['sku_duplicate'].value_counts()

sku_duplicate
False    9224
True        8
Name: count, dtype: int64

In [53]:
inventory_clean['sku_quality'] = 'Valid SKU'

inventory_clean.loc[
    inventory_clean['sku_missing'],
    'sku_quality'
] = 'Missing / Invalid SKU'

inventory_clean.loc[
    inventory_clean['sku_duplicate'],
    'sku_quality'
] = 'Duplicate / Conflicting SKU'

In [54]:
inventory_clean['sku_quality'].value_counts()

sku_quality
Valid SKU                      9165
Missing / Invalid SKU            59
Duplicate / Conflicting SKU       8
Name: count, dtype: int64

In [55]:
inventory_clean.isnull().sum()

sku              59
design_no         0
stock             0
category          0
size              0
color             0
sku_missing       0
stock_status      0
sku_duplicate     0
sku_quality       0
dtype: int64

In [56]:
inventory_clean.to_csv(
    project_folder / 'Inventory_Cleaned.csv',
    index=False
)

In [57]:
project_folder / 'Inventory_Cleaned.csv'

WindowsPath('C:/Users/pavan/OneDrive/Desktop/E-Commerce SalesDataset/Inventory_Cleaned.csv')

In [2]:
amazon_clean = pd.read_csv(project_folder / 'Amazon_Sales_Cleaned.csv',
                           parse_dates = ['date'],
                           low_memory = False)

NameError: name 'pd' is not defined

In [3]:
import pandas as pd

In [5]:
from pathlib import Path

project_folder = Path(
    r'C:\Users\pavan\OneDrive\Desktop\E-Commerce SalesDataset'
)

In [6]:
amazon_clean = pd.read_csv(project_folder / 'Amazon_Sales_Cleaned.csv',
                           parse_dates = ['date'],
                           low_memory = False)

In [7]:
amazon_clean.shape

(128975, 36)

In [8]:
inventory_clean = pd.read_csv(project_folder / 'Inventory_Cleaned.csv')

In [9]:
inventory_clean.shape

(9232, 10)

In [11]:
inventory_merge_ready = inventory_clean[
    inventory_clean['sku_quality'] == 'Valid SKU'].copy()

In [12]:
inventory_merge_ready.shape

(9165, 10)

In [13]:
inventory_for_merge = inventory_merge_ready[
    [
        'sku',
        'design_no',
        'stock',
        'color',
        'stock_status',
        'sku_quality']].copy()

sales_inventory = amazon_clean.merge(
    inventory_for_merge,
    on = 'sku',
    how = 'left',
    validate = 'many_to_one',
    indicator = 'inventory_match')

In [14]:
sales_inventory.shape

(128975, 42)

In [16]:
sales_inventory['inventory_match'].value_counts()

inventory_match
both          121269
left_only       7706
right_only         0
Name: count, dtype: int64

In [17]:
sales_without_inventory = sales_inventory[
    sales_inventory['inventory_match'] == 'left_only'
].copy()

sales_without_inventory[
    ['sku', 'status', 'qty', 'amount']
].head(10)

                           sku                        status  qty  amount
8          SET200-KR-NP-A-XXXL                     Cancelled    0     NaN
10              JNE3160-KR-G-S                       Shipped    1   685.0
27           PJNE2199-KR-N-4XL                       Shipped    1   459.0
42          JNE2153-KR-278-A-M  Shipped - Delivered to Buyer    1   424.0
53   JNE1407-BLACK-KR-UDF18-XL                       Shipped    1   390.0
61          JNE2270-KR-487-A-M                       Shipped    1   518.0
67              JNE3645-TP-N-L                       Shipped    1   432.0
70             JNE3068-KR-A-XL  Shipped - Delivered to Buyer    1   696.0
109             JNE3648-TP-N-M  Shipped - Delivered to Buyer    1   518.0
115           SET397-KR-NP  -M                       Shipped    1  1186.0

In [18]:
sales_without_inventory['status_group'].value_counts(dropna=False)

status_group
Shipped / In Process    4466
Delivered               1907
Cancelled               1106
Return / Rejected        156
Pending                   71
Name: count, dtype: int64

In [19]:
matched_sales = sales_inventory[
    sales_inventory['inventory_match'] == 'both'
].copy()

matched_sales['stock_status'].value_counts()

stock_status
In Stock        86746
Low Stock       32395
Out of Stock     2128
Name: count, dtype: int64

In [20]:
demand_sales = matched_sales[
    matched_sales['status_group'].isin(
        ['Delivered', 'Shipped / In Process']
    )
].copy()

demand_sales.shape

(101216, 42)

In [23]:
restock_priority = (
    demand_sales
    .groupby(
        [
            'sku',
            'category',
            'design_no',
            'color',
            'stock',
            'stock_status'
        ],
        as_index=False
    )
    .agg(
        units_sold=('qty', 'sum'),
        sales_revenue=('amount', 'sum'),
        sales_records=('order_id', 'count')
    )
)

restock_priority = (
    restock_priority[
        restock_priority['stock_status'].isin(
            ['Low Stock', 'Out of Stock']
        )
    ]
    .sort_values(
        ['stock', 'units_sold'],
        ascending=[True, False]
    ))

In [24]:
restock_priority.head(10)

,sku,category,design_no,color,stock,stock_status,units_sold,sales_revenue,sales_records
4109,JNE3797-KR-XXL,Western Dress,JNE3797,Green,0.0,Out of Stock,336,241383.0,336
2861,JNE3510-KR-M,Kurta,JNE3510,Grey,0.0,Out of Stock,112,49632.0,112
4130,JNE3800-KR-XXL,Western Dress,JNE3800,Mustard,0.0,Out of Stock,87,64628.0,87
600,J0095-SET-XXL,Set,J0095,Blue,0.0,Out of Stock,74,45748.0,73
4319,JNE3861-DR-L,Western Dress,JNE3861,Red,0.0,Out of Stock,53,42362.0,53
2696,JNE3461-KR-XXXL,Kurta,JNE3461,Teal,0.0,Out of Stock,49,18875.0,49
4037,JNE3787-KR-S,Kurta,JNE3787,Blue,0.0,Out of Stock,41,19358.0,41
6200,SET363-KR-NP-L,Set,SET363,Pink,0.0,Out of Stock,39,48633.0,39
5743,SET282-KR-PP-XXXL,Set,SET282,Yellow,0.0,Out of Stock,34,34849.0,34
4181,JNE3810-KR-L,Kurta,JNE3810,Black,0.0,Out of Stock,32,18273.0,31

In [27]:
category_restock_risk = (
    restock_priority
    .groupby('category', as_index=False)
    .agg(
        at_risk_skus=('sku', 'nunique'),
        demand_units=('units_sold', 'sum'),
        historical_sales_revenue=('sales_revenue', 'sum')).sort_values(  'historical_sales_revenue',
        ascending=False))

In [28]:
category_restock_risk

        category  at_risk_skus  demand_units  historical_sales_revenue
5            Set           793         11784                 9707656.0
3          Kurta           861          8882                 4028433.0
7  Western Dress           233          5418                 3976713.0
6            Top           339          2202                 1042984.0
2   Ethnic Dress            34           291                  206142.0
1         Bottom            92           205                   70643.0
4          Saree            24            33                   24815.0
0         Blouse            20            38                   12734.0

In [30]:
out_of_stock_category_risk = (restock_priority[restock_priority['stock_status'] == 'Out of Stock'].groupby('category', as_index = False).agg(
    out_of_stock_skus = ('sku','nunique'),
    demand_units = ('units_sold','sum'),
    historical_sales_revenue = ('sales_revenue','sum')).sort_values('historical_sales_revenue',ascending = False))

In [32]:
out_of_stock_category_risk

        category  out_of_stock_skus  demand_units  historical_sales_revenue
4            Set                 72           505                  454177.0
6  Western Dress                 20           599                  448481.0
2          Kurta                 75           605                  299873.0
5            Top                 29           110                   58479.0
1   Ethnic Dress                  6            13                    8229.0
3          Saree                  3             5                    3473.0
0         Bottom                  3             6                    3319.0

In [34]:
delivered_sales = sales_inventory[sales_inventory['status_group'] == 'Delivered'].copy()

In [36]:
delivered_sales.shape

(28769, 42)

In [37]:
delivered_sales['amount'].isnull().sum()

np.int64(8)

In [39]:
delivered_revenue_sales = delivered_sales.dropna(
    subset=['amount']).copy()

In [41]:
delivered_revenue_sales.shape

(28761, 42)

In [43]:
delivered_kpis = pd.Series({
    'delivered_orders': delivered_revenue_sales['order_id'].nunique(),
    'units_sold': delivered_revenue_sales['qty'].sum(),
    'delivered_revenue': delivered_revenue_sales['amount'].sum()
})

In [44]:
delivered_kpis

delivered_orders        26566.0
units_sold              28886.0
delivered_revenue    18650815.0
dtype: float64

In [45]:
delivered_order_summary = ( delivered_revenue_sales.groupby('order_id', as_index = False).agg(
    order_revenue = ('amount', 'sum'),
    order_units = ('qty','sum')))

average_order_value = delivered_order_summary['order_revenue'].mean()

In [46]:
average_order_value

np.float64(702.0558232327035)

In [51]:
monthly_delivered_sales = (
    delivered_revenue_sales.groupby(['month_number', 'month_name'], as_index = False).agg(
        delivered_orders = ('order_id', 'nunique'),
        units_sold = ('qty','sum'),
        revenue = ('amount', 'sum')).sort_values('month_number')
)

In [52]:
monthly_delivered_sales

   month_number month_name  delivered_orders  units_sold    revenue
0             3      March                16          16    10170.0
1             4      April             11093       12135  7453429.0
2             5        May              9549       10441  6932202.0
3             6       June              5908        6294  4255014.0

In [53]:
monthly_date_coverage = (
    delivered_revenue_sales
    .groupby(['month_number', 'month_name'], as_index=False)
    .agg(
        first_sale_date=('date', 'min'),
        last_sale_date=('date', 'max'),
        days_with_sales=('date', 'nunique')
    )
    .sort_values('month_number')
)

monthly_date_coverage

   month_number month_name first_sale_date last_sale_date  days_with_sales
0             3      March      2022-03-31     2022-03-31                1
1             4      April      2022-04-01     2022-04-30               30
2             5        May      2022-05-01     2022-05-31               31
3             6       June      2022-06-01     2022-06-26               26

In [1]:
monthly_sales_daily = monthly_delivered_sales.merge(monthly_date_coverage[['month_number', 'days_with_sales']],
                                                    on = 'month_number',
                                                    how = 'left')

monthly_sales_daily['revenue_per_day'] = (monthly_sales_daily['revenue'] / 
                                          monthly_sales_daily['days_with_sales']).round(2)

NameError: name 'monthly_delivered_sales' is not defined

In [2]:
import pandas as pd
from pathlib import Path

project_folder = Path(
    r'C:\Users\pavan\OneDrive\Desktop\E-Commerce SalesDataset'
)

amazon_clean = pd.read_csv(
    project_folder / 'Amazon_Sales_Cleaned.csv',
    parse_dates=['date'],
    low_memory=False
)

inventory_clean = pd.read_csv(
    project_folder / 'Inventory_Cleaned.csv',
    low_memory=False
)

amazon_clean['sku'] = amazon_clean['sku'].astype('string').str.strip()
inventory_clean['sku'] = inventory_clean['sku'].astype('string').str.strip()

inventory_merge_ready = inventory_clean[
    inventory_clean['sku_quality'] == 'Valid SKU'
].copy()

inventory_for_merge = inventory_merge_ready[
    ['sku', 'design_no', 'stock', 'color', 'stock_status', 'sku_quality']
].copy()

sales_inventory = amazon_clean.merge(
    inventory_for_merge,
    on='sku',
    how='left',
    validate='many_to_one',
    indicator='inventory_match'
)

matched_sales = sales_inventory[
    sales_inventory['inventory_match'] == 'both'
].copy()

demand_sales = matched_sales[
    matched_sales['status_group'].isin(
        ['Delivered', 'Shipped / In Process']
    )
].copy()

delivered_sales = sales_inventory[
    sales_inventory['status_group'] == 'Delivered'
].copy()

delivered_revenue_sales = delivered_sales.dropna(
    subset=['amount']
).copy()

In [3]:
sales_inventory.shape

(128975, 42)

In [4]:
category_delivered_sales = (
    delivered_revenue_sales
    .groupby('category', as_index=False)
    .agg(
        delivered_orders=('order_id', 'nunique'),
        units_sold=('qty', 'sum'),
        revenue=('amount', 'sum')
    )
    .sort_values('revenue', ascending=False)
)

category_delivered_sales

        category  delivered_orders  units_sold    revenue
5            Set             10135       10675  8800562.0
3          Kurta              9613       10497  4715208.0
7  Western Dress              4956        5216  3868616.0
6            Top              1828        1924   948734.0
2   Ethnic Dress               230         237   165465.0
0         Blouse               161         172    85444.0
1         Bottom               130         142    48615.0
4          Saree                16          23    18171.0

In [5]:
state_delivered_sales = (delivered_revenue_sales.groupby('ship_state', as_index = False).agg(
    delivered_orders = ('order_id', 'nunique'),
    units_sold = ('qty','sum'),
    revenue = ('amount', 'sum')).sort_values('revenue', ascending = False))

In [6]:
state_delivered_sales.head(10)

        ship_state  delivered_orders  units_sold    revenue
20     MAHARASHTRA              4582        4984  3135062.0
15       KARNATAKA              3350        3638  2279856.0
34   UTTAR PRADESH              2282        2452  1669881.0
31       TELANGANA              2140        2417  1551447.0
30      TAMIL NADU              2197        2424  1466364.0
16          KERALA              1567        1694  1079132.0
8            DELHI              1459        1592  1040241.0
1   ANDHRA PRADESH              1084        1199   772127.0
36     WEST BENGAL              1139        1205   749127.0
10         GUJARAT              1035        1121   732260.0

In [7]:
sales_inventory.to_csv( project_folder / 'Sales_Inventory_Analysis.csv',
                        index = False)

In [10]:
import os

print("Jupyter folder:")
print(os.getcwd())

print("\nFiles in this folder:")
print(os.listdir())

Jupyter folder:
C:\Users\pavan\Fashion_Retail_Analytical_Project

Files in this folder:
['.ipynb_checkpoints', 'Amazon_Sale_Report.ipynb', 'Untitled.ipynb']

In [12]:
import pandas as pd

amazon_clean = pd.read_csv(
    r"C:\Users\pavan\OneDrive\Desktop\E-Commerce SalesDataset\Amazon_Sales_Cleaned.csv",
    low_memory=False
)

print(amazon_clean.shape)

(128975, 36)

In [13]:
amazon_github = amazon_clean.sample(
    n=30000,
    random_state=42
)

amazon_github.to_csv(
    "Amazon_Sales_Cleaned_GitHub.csv",
    index=False
)

In [14]:
import os

size_mb = os.path.getsize("Amazon_Sales_Cleaned_GitHub.csv") / (1024 * 1024)

print(f"GitHub file size: {size_mb:.2f} MB")
print("Shape:", amazon_github.shape)

GitHub file size: 18.07 MB
Shape: (30000, 36)

In [15]:
import os

print(os.path.abspath("Amazon_Sales_Cleaned_GitHub.csv"))
print(os.path.exists("Amazon_Sales_Cleaned_GitHub.csv"))

C:\Users\pavan\Fashion_Retail_Analytical_Project\Amazon_Sales_Cleaned_GitHub.csv
True

In [16]:
amazon_github.to_csv(
    r"C:\Users\pavan\OneDrive\Desktop\E-Commerce SalesDataset\Amazon_Sales_Cleaned_GitHub.csv",
    index=False
)

print("CSV saved successfully")

CSV saved successfully